name: push-action
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build app
        run: dotnet build PowerCollections
      - name: Test app
        run: dotnet test PowerCollections.Tests