name: publish-and-release-nuget
on: workflow_dispatch
jobs:
  pack-nuget:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pack nuget
      run: dotnet pack PowerCollections/PowerCollections/PowerCollections.csproj -c Release
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: package/Release/

  publish-nuget:
    runs-on: windows-latest
    needs: pack-nuget
    steps:
    - name: Download artifacts of pack-nuget
      uses: actions/download-artifact@v3
      with:
        name: package
    - name: Publish nuget package
      run: |
        $package = Get-ChildItem package\Release\*.nupkg | Sort-Object LastWriteTime
        dotnet nuget push $package.fullname --api-key ${{ secrets.PUBLISH_NUGET_TOKEN }} --source https://nuget.pkg.github.com/lckish/index.json --skip-duplicate

  release-nuget:
    runs-on: windows-latest
    needs: pack-nuget
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get version
      id: getVersion
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'PowerCollections/PowerCollections/PowerCollections.csproj'
        xPath: '//VersionPrefix'
    - name: Download artifacts of pack-nuget
      uses: actions/download-artifact@v3
      with:
        name: package
    - name: Release nuget package
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'package\Release\*.nupkg'
        tag: v${{ steps.getVersion.outputs.info }}
        token: ${{ secrets.ACTION_TOKEN }}